version: 2.1

jobs:
  working_directory: ~/workspace
  setup:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - run:
          name: install libraries
          command: npm i
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - run:
          name: check node version
          command: node -v
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/node:16.6.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            97:59:82:36:fc:b3:0a:92:c5:eb:9d:0e:65:05:32:b4
      - run:
          name: log in github
          command: |
            git config --global user.email "ichigomomiji436@gmail.com"
            git config --global user.name "Momijiichigo"
      
      - run:
          name: Deploy
          command: npm run deploy
workflows:
  build&deploy:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - setup
      - deploy:
          requires:
            - build